@BankingSystem_HostAddress = http://localhost:5274
@Admin_AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODU5ZDk4OC00NDM1LTQ4MzUtYjczMi1lMmQyNjEzYjgyNDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsInBob25lIjoiKzI1NTY3NTc1NzU3NSIsImV4cCI6MTc2NjY4NzUyNSwiaXNzIjoiQmFua2luZ1N5c3RlbSIsImF1ZCI6IkJhbmtpbmdTeXN0ZW1Vc2VycyJ9.y_c26TlCNchlvZ_3jb2YPLBidSsSDKPnx2r-yaMnpBc
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODU5ZDk4OC00NDM1LTQ4MzUtYjczMi1lMmQyNjEzYjgyNDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsInBob25lIjoiKzI1NTY3NTc1NzU3NSIsImV4cCI6MTc2NjY1NTk1MiwiaXNzIjoiQmFua2luZ1N5c3RlbSIsImF1ZCI6IkJhbmtpbmdTeXN0ZW1Vc2VycyJ9.4jYHVVPhZsbt7yFPAqkpz_AcTx6Xz4aQfHkpnNWVZSo

@Customer_AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDIyZGFiNi1kNTZmLTRiNzAtOGNkZS0yY2FiODI4Mzc0MmIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsInBob25lIjoiKzI1OTkyOTk2Njc3IiwiZXhwIjoxNzY2ODg0ODY3LCJpc3MiOiJCYW5raW5nU3lzdGVtIiwiYXVkIjoiQmFua2luZ1N5c3RlbVVzZXJzIn0.zQu0ZIYyzaCLRHdMsPHI08x0Lt0sCkEuVJtfZ2HKz24
###
GET {{BankingSystem_HostAddress}}/api/admin/users?pageNumber=1&pageSize=10
Authorization: Bearer {{Admin_AccessToken}}
Accept: application/json


###
POST {{BankingSystem_HostAddress}}/api/admin/users/register
Accept: application/json
Authorization: Bearer {{Admin_AccessToken}}
Content-Type: application/json

{
    "Name": "Kebron Marken",
    "phoneNumber": "+25992996677",
    "password": "1234"
}

###
PUT {{BankingSystem_HostAddress}}/api/admin/users/e5fa3bdb-045c-4562-9d7a-c6d75acccfc1
Accept: application/json
Authorization: Bearer {{Admin_AccessToken}}
Content-Type: application/json

{
    "Name": "Mona M. Smith",
    "phoneNumber": "+255675357575",
    "password": "adam@12345"
}

########################################## Authentication APIs ##########################################
POST {{BankingSystem_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "phoneNumber": "+251996670943",
    "password": "4321"
}

###
POST {{BankingSystem_HostAddress}}/api/auth/logout
Accept: application/json
Content-Type: application/json

{
    "refreshToken": "ZLPNnkgVjzCNinXyX4aXDR1uBIcar8TZB5cT7LOSKBqUEvZZoTwTGg_HL86OVLv-rGcbrfoxR0tD9CSCtstPcw"
    }

########################################## Account Management APIs ##########################################
POST {{BankingSystem_HostAddress}}/api/accounts

###
DELETE {{BankingSystem_HostAddress}}/api/admin/users/0859D988-4435-4835-B732-E2D2613B8241


###
GET {{BankingSystem_HostAddress}}/api/admin/accounts/7a6ab6d0-2997-41aa-8eef-177e957c9cd5/user

###
GET {{BankingSystem_HostAddress}}/api/user/me
Authorization: Bearer {{Customer_AccessToken}}

###
GET {{BankingSystem_HostAddress}}/api/transactions?pageNumber=1&pageSize=10
Authorization: Bearer {{Customer_AccessToken}}

###
PUT {{BankingSystem_HostAddress}}/api/admin/users/4422dab6-d56f-4b70-8cde-2cab8283742b
Content-Type: application/json

{
    "phoneNumber": "+251975357575",
    "password": "adam@12345",
    "name": "Mariana Smith",
    "isActive": false
}

